# Generated by Django 5.1.6 on 2025-02-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='image',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='website',
        ),
    ]
