# Generated by Django 5.1.6 on 2025-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_campuses_issues_studentsubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmissions',
            name='student_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
