# Generated by Django 5.1.6 on 2025-03-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_studentsubmissions_student_id_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmissions',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubmissions',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsubmissions',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
